{% set name = "mixer" %}
{% set version = "7.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mixer-{{ version }}.tar.gz
  sha256: 9b3f1a261b56d8f2394f39955f83adbc7ff3ab4bb1065ebfec19a10d3e8501e0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - faker >=5.4.0,<12.1

test:
  imports:
    - mixer
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/klen/mixer
  summary: Mixer -- Is a fixtures replacement. Supported Django ORM, SqlAlchemy ORM, Mongoengine ODM and custom python objects.
  doc_url: https://pythonhosted.org/mixer/
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - julian-belina
